# Generated by Django 5.1.3 on 2024-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='day_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
