# Generated by Django 5.1.3 on 2024-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersetting_day_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='days_associated',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='time_required',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
